WIP: Introduce CRC cards
hypersousage/console-organizer pull request #2
Opened 2021-03-26 12:00 UTC by hypersousage

2021-03-27 20:19 UTC, nvamelichev requested changes

2021-03-27 20:19 UTC, nvamelichev commented on crc_cards.md
> +Ответственность: Описывает структуру задачи, содржит поля: ID, описание, приоритет, время напоминания, время создания, дедлайн, тег, период напоминания, статус.
Маленькое замечание про "тег": как мне кажется, стоит поддержать множество тегов для задачи.
Например, в TODO.txt вполне может быть задача "Постричь газон #дом #спорт #кровь_пот_и_слёзы" :-D

2021-03-27 20:19 UTC, nvamelichev commented on crc_cards.md
> +Ответственность: Имеет хендлеры для каждой из команд (add, show, delete, etc.). Каждый из хендлеров получает аргументы командной строки, переданные пользователем, обрабатывает их и вызывает соответст
Я правильно понял, что CommandHandler' у вас связывают StorageManager/FormatPrinter/NotificationManager воедино для выполнения пользовательской задачи?

2021-03-27 20:19 UTC, nvamelichev commented on crc_cards.md
> +Ответственность: Форматирует и выводит информацию о задачах пользователя. Цвет выведенной задачи меняется в зависимости от статуса.
* Подумайте, может ли в вашем продукте быть несколько разных реализаций FormatPrinter? Например, если вы захотите экспортировать задачи в каком-нибудь известном формате, типа [iCalendar](https://en.wikipedia.org/wiki/ICalendar), чтобы увидеть их в каком-нибудь Google Calendar на телефоне. Если такой юзкейс достаточно вероятен для ваших основных пользователей - FormatPrinter стоит сделать не конкретным классом, а интерфейсом или абстрактным базовым классом.
* Naming: я бы переименовал "печататель-формата" (FormatPrinter) во что-нибудь более понятное, скажем, TaskWriter или TaskOutput ("вывод задач").
* Я бы убрал из CRC-карточек информацию про цветной вывод - это уже очень подробные детали реализации. 
* Ещё про цветной вывод: **не все консоли поддерживают цвет, а в случае, когда stdout перенправлен в файл - цветной вывод и вовсе вреден.** Значит, в вашем продукте надо будет обнаруживать, когда нужно декорировать задачи, а когда нет :-) 
    * Совет (**не обязательно** ему следовать): лично я реализовал бы цветной вывод на консоль с помощью паттерна "Декоратор": базовый вывод на консоль в классе ConsoleTaskOutput, а раскраска задач в соответствии со статусом - в другом классе, декорирующем ConsoleTaskOutput.

2021-03-27 20:19 UTC, nvamelichev commented on crc_cards.md
> +Ответственность: Взаимодейстует с ОС и шедулит уведомления.
* Расскажите немного о том, кто будет просить NotificationManager зашедулить уведомления? Какой-то из обработчиков команд от пользователя? Отдельный класс, который опрашивает хранилище задач на предмет изменений, или сам подписан на события "задача добавлена/удалена/изменена/..." (см. паттерн "Наблюдатель")?
* Будет ли у NotificationManager несколько возможных реализаций, в зависимости от ОС (и, возможно, какая-то ОС-независимая реализация, которая просто будет печатать сообщения о приближающихся задачах в консоль)? Если да, то возможно имеет смысл применение паттерна "абстрактная фабрика": построить фабрику по производству NotificationManager'ов, разные ОС - разные фабрики. Возможно, что это оверкилл: всё-таки я бы не считал нотификации Абсолютно Основной Фичей. 
Решайте тут сами, главное - сообщите о вашем решении мне :-)

2021-04-05 19:41 UTC, yambulatof commented on crc_cards.md
> +Ответственность: Имеет хендлеры для каждой из команд (add, show, delete, etc.). Каждый из хендлеров получает аргументы командной строки, переданные пользователем, обрабатывает их и вызывает соответст
Да, всё верно.

2021-04-05 20:03 UTC, yambulatof commented on crc_cards.md
> +Ответственность: Взаимодейстует с ОС и шедулит уведомления.
* Предполагался механизм взаимодействия напрямую с CommandHandler: когда он встречает запрос на добавление напоминания в хендлере `add`, он дополнительно вызывает метод внутри NotificationManager, который шедулит уведомление. 
* Предполагается изначально сделать поддержку уведомлений только на MacOS (специфика команды), но оставить возможность добавления другой операционной системы. Так что да, NotificationManager сделаем абстрактной фабрикой.

2021-04-05 20:06 UTC, yambulatof commented
Обновили описание crc-карт @nvamelichev

2021-04-05 21:11 UTC, nvamelichev commented on crc_cards.md
> +Ответственность: Взаимодейстует с ОС и шедулит уведомления.
> Предполагался механизм взаимодействия напрямую с CommandHandler: когда он встречает запрос на добавление напоминания в хендлере add, он дополнительно вызывает метод внутри NotificationManager, который шедулит уведомление.

Ага, понятно. Но если таску удаляют или изменяют её время начала/конца - думаю, менеджер нотификаций тоже должен об этом узнать, и убрать/обновить нотификацию в ОС. А это уже похоже на повод заюзать паттерн "Наблюдатель" :-)

2021-04-05 22:26 UTC, nvamelichev approved these changes
Первую итерацию ОО-дизайна я **принимаю условно** :+1:. В целом - уже неплохо + я вижу улучшения по сравнению с предыдущей версией.
**Время писать код, т.к. первые релизы проектов мы смотрим на этой неделе: в пятницу, 9 апреля**. Сосредоточьтесь на **абсолютно необходимом**: ваш код должен собираться в исполняемый JAR-файл с помощью Maven или Gradle, этот JAR-файл должен запускаться через `java -jar <имя_файла.jar>`, **должны быть реализованы самые жизненно важные пользовательские сценарии.**

----

Вижу, что вы немного не успели к дедлайну (который был продлён до конца дня воскресенья, 4 апреля). 
**Не волнуйтесь:** главное в изучении промышленного программирования - не пройти N произвольных испытаний в сжатые сроки :1st_place_medal:, а сделать хороший, потенциально полезный проект и получить практические навыки командной разработки :-)

**Забеспокоиться стоит**, если вы не сможете показать ни одной демки вашего проекта в ближайшие пару недель. Думаю, это маловероятно, с учётом практически готового дизайна :-)

**На будущее: пожалуйста, предупреждайте заранее, если не успеваете (можно в личку).** Дедлайны позволяют мне понять, когда можно смотреть на готовую часть работы над проектом. Если у вас что-то уже готово раньше - сразу призывайте меня: пишите `@nvamelichev` в комментарии к Issue или PR на гитхабе. Если вы чуть-чуть не успеваете - пишите в личку (телеграм, почта).

----

Что стоит ещё доработать:
* Детализировать диаграмму последовательности UML в #3. Хочется увидеть чуть больше деталей, кто кого вызывает и почему при создании, изменении и удалении задач. См. также мои предыдущие комментарии про UML-диаграммы: https://github.com/hypersousage/console-organizer/pull/3#issuecomment-808797516
* Додумать про [работу с нотификациями](https://github.com/hypersousage/console-organizer/pull/2#discussion_r607337069), но не прямщас. **Пусть сначала проект "взлетит"** - начнёт чуть-чуть создавать, удалять и перечислять задачки из файла TODO.txt.

2021-04-05 22:26 UTC, nvamelichev commented on crc_cards.md
> +Ответственность: Описывает структуру задачи, содржит поля: ID, описание, приоритет, время напоминания, время создания, дедлайн, набор тегов, период напоминания, статус.
мелочь: опечатка: со**др**жит -> со**дер**жит

2021-04-05 22:26 UTC, nvamelichev commented on crc_cards.md
> +Ответственность: Имеет хендлеры для каждой из команд (add, show, delete, etc.). Каждый из хендлеров получает аргументы командной строки, переданные пользователем, обрабатывает их и вызывает соответст
:+1:

2021-04-16 10:49 UTC, merged